name: freehand-US
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.0.0
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - attrs=23.1.0
  - biopython=1.82
  - blas=2.120
  - blas-devel=3.9.0
  - blinker=1.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.24.0
  - ca-certificates=2023.11.17
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - cftime=1.6.3
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cudatoolkit=11.8.0
  - curl=8.1.2
  - cycler=0.12.1
  - dataclasses=0.8
  - dbus=1.13.18
  - eigen=3.4.0
  - expat=2.5.0
  - fasteners=0.17.3
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.13.1
  - fontconfig=2.14.2
  - fonttools=4.47.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2023.12.2
  - fvcore=0.1.5.post20221221
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.3
  - glib-tools=2.78.3
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - google-auth=2.25.2
  - google-auth-oauthlib=1.2.0
  - griddataformats=1.0.2
  - grpcio=1.60.0
  - gsd=3.2.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.8.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.1
  - iopath=0.1.9
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libcurl=8.1.2
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgrpc=1.60.0
  - libhwloc=2.9.1
  - libiconv=1.17
  - libitk=5.3.0
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.9.1
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.4.0
  - libuuid=2.38.1
  - libuv=1.46.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.3
  - libxml2=2.10.4
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - markdown=3.5.1
  - markupsafe=2.1.3
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - mda-xdrlib=0.2.0
  - mdanalysis=2.6.1
  - mkl=2022.2.1
  - mkl-devel=2022.2.1
  - mkl-include=2022.2.1
  - mmtf-python=1.1.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mrcfile=1.4.3
  - msgpack-python=1.0.7
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql=5.7.20
  - ncurses=6.4
  - netcdf4=1.6.3
  - nettle=3.6
  - networkx=3.2.1
  - numpy=1.26.2
  - oauthlib=3.2.2
  - openblas=0.3.25
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.2.0
  - packaging=23.2
  - pandas=2.1.4
  - patsy=0.5.4
  - pcre2=10.42
  - pillow=10.0.1
  - pip=23.3.2
  - ply=3.11
  - portalocker=2.8.2
  - protobuf=4.24.4
  - pthread-stubs=0.4
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pyedr=0.8.0
  - pyjwt=2.8.0
  - pyopenssl=23.3.0
  - pyparsing=3.1.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytng=0.3.1
  - pytorch-mutex=1.0
  - pytorch3d=0.7.5
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - qt-main=5.15.2
  - re2=2023.06.02
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - seaborn=0.13.0
  - seaborn-base=0.13.0
  - setuptools=68.2.2
  - simpleitk=2.2.1
  - sip=6.7.12
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.44.2
  - statsmodels=0.14.1
  - sympy=1.12
  - tabulate=0.9.0
  - tbb=2021.9.0
  - tensorboard=2.15.1
  - tensorboard-data-server=0.7.0
  - termcolor=2.3.0
  - threadpoolctl=3.2.0
  - tidynamics=1.1.2
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=2.1.0
  - werkzeug=3.0.1
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.5
  - yacs=0.1.8
  - yaml=0.2.5
  - yarl=1.9.3
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - torch==2.1.0
      - torchvision==0.16.0
      - triton==2.1.0
